export const TEAM_INFO = {
  'red_bull': {
    id: 'red_bull',
    fullName: 'Oracle Red Bull Racing',
    shortName: 'Red Bull',
    color: '#3671C6',
    nationality: 'Austrian',
    base: 'Milton Keynes, UK',
    engineSupplier: 'Ford RBPT',
    foundedYear: 2005,
    championshipYears: [2010, 2011, 2012, 2013, 2022, 2023],
    driverChampions: ['Sebastian Vettel (2010–2013)', 'Max Verstappen (2021–2024)'],
    notableCars: ['RB7', 'RB9', 'RB19'],
    description: 'Dominant constructor of the early 2010s and again in 2022–2023, Red Bull Racing has won six Constructors\' Championships.',
  },
  'ferrari': {
    id: 'ferrari',
    fullName: 'Scuderia Ferrari HP',
    shortName: 'Ferrari',
    color: '#E8002D',
    nationality: 'Italian',
    base: 'Maranello, Italy',
    engineSupplier: 'Ferrari',
    foundedYear: 1950,
    championshipYears: [1961,1964,1975,1976,1977,1979,1982,1983,1999,2000,2001,2002,2003,2004,2007,2008],
    driverChampions: ['Fangio', 'Surtees', 'Lauda', 'Scheckter', 'Schumacher (x5)', 'Räikkönen'],
    notableCars: ['F2004', 'F2007', 'SF90'],
    description: 'The most iconic team in Formula 1 history, Ferrari has competed in every season since the World Championship began in 1950.',
  },
  'mercedes': {
    id: 'mercedes',
    fullName: 'Mercedes-AMG Petronas F1 Team',
    shortName: 'Mercedes',
    color: '#27F4D2',
    nationality: 'German',
    base: 'Brackley, UK',
    engineSupplier: 'Mercedes',
    foundedYear: 2010,
    championshipYears: [2014,2015,2016,2017,2018,2019,2020,2021],
    driverChampions: ['Lewis Hamilton (2014–2015, 2017–2020)', 'Nico Rosberg (2016)'],
    notableCars: ['W05', 'W11'],
    description: 'Dominated the hybrid era with an unprecedented 8 consecutive Constructors\' Championships from 2014 to 2021.',
  },
  'mclaren': {
    id: 'mclaren',
    fullName: 'McLaren Formula 1 Team',
    shortName: 'McLaren',
    color: '#FF8000',
    nationality: 'British',
    base: 'Woking, UK',
    engineSupplier: 'Mercedes',
    foundedYear: 1966,
    championshipYears: [1974,1984,1985,1988,1989,1990,1991,1998],
    driverChampions: ['Emerson Fittipaldi', 'James Hunt', 'Lauda', 'Prost', 'Senna (x3)', 'Häkkinen (x2)'],
    notableCars: ['MP4/4', 'MP4/13'],
    description: 'One of the most successful teams of the 1980s and 90s, resurgent in the 2020s with Norris and Piastri.',
  },
  'aston_martin': {
    id: 'aston_martin',
    fullName: 'Aston Martin Aramco F1 Team',
    shortName: 'Aston Martin',
    color: '#229971',
    nationality: 'British',
    base: 'Silverstone, UK',
    engineSupplier: 'Honda RBPT',
    foundedYear: 2021,
    championshipYears: [],
    driverChampions: [],
    notableCars: ['AMR23'],
    description: 'Rebranded from Racing Point in 2021, competing with Honda power from 2026.',
  },
  'alpine': {
    id: 'alpine',
    fullName: 'BWT Alpine F1 Team',
    shortName: 'Alpine',
    color: '#FF87BC',
    nationality: 'French',
    base: 'Enstone, UK',
    engineSupplier: 'Renault',
    foundedYear: 1981,
    championshipYears: [2005, 2006],
    driverChampions: ['Fernando Alonso (2005–2006)'],
    notableCars: ['R25', 'R26'],
    description: 'Racing as Renault when Alonso won back-to-back titles; rebranded as Alpine in 2021.',
  },
  'williams': {
    id: 'williams',
    fullName: 'Williams Racing',
    shortName: 'Williams',
    color: '#64C4FF',
    nationality: 'British',
    base: 'Grove, UK',
    engineSupplier: 'Mercedes',
    foundedYear: 1978,
    championshipYears: [1980,1981,1982,1983,1986,1987,1992,1993,1994,1996,1997],
    driverChampions: ['Jones', 'Rosberg', 'Piquet', 'Mansell', 'Prost', 'Hill', 'Villeneuve'],
    notableCars: ['FW14B', 'FW18'],
    description: 'Seven-time Constructors\' Champions and one of the most successful teams of the 1980s and 90s.',
  },
  'haas': {
    id: 'haas',
    fullName: 'MoneyGram Haas F1 Team',
    shortName: 'Haas',
    color: '#B6BABD',
    nationality: 'American',
    base: 'Kannapolis, USA',
    engineSupplier: 'Ferrari',
    foundedYear: 2016,
    championshipYears: [],
    driverChampions: [],
    notableCars: ['VF-22'],
    description: 'The only American-owned team on the grid, entering F1 in 2016 with Ferrari power.',
  },
  'rb': {
    id: 'rb',
    fullName: 'Visa Cash App RB Formula One Team',
    shortName: 'RB',
    color: '#6692FF',
    nationality: 'Italian',
    base: 'Faenza, Italy',
    engineSupplier: 'Honda RBPT',
    foundedYear: 2006,
    championshipYears: [],
    driverChampions: [],
    notableCars: ['STR3'],
    description: 'Red Bull\'s sister team, formerly known as Toro Rosso and AlphaTauri, serving as a driver development program.',
  },
  'sauber': {
    id: 'sauber',
    fullName: 'Stake F1 Team Kick Sauber',
    shortName: 'Sauber',
    color: '#52E252',
    nationality: 'Swiss',
    base: 'Hinwil, Switzerland',
    engineSupplier: 'Ferrari',
    foundedYear: 1993,
    championshipYears: [],
    driverChampions: [],
    notableCars: ['C32'],
    description: 'Transitioning to become the Audi works team from 2026, marking a new chapter in the team\'s history.',
  },
}

export const TEAM_NAME_MAP = {
  'Red Bull Racing':    'red_bull',
  'Red Bull':           'red_bull',
  'Ferrari':            'ferrari',
  'Mercedes':           'mercedes',
  'McLaren':            'mclaren',
  'Aston Martin':       'aston_martin',
  'Alpine':             'alpine',
  'Williams':           'williams',
  'Haas F1 Team':       'haas',
  'Haas':               'haas',
  'RB':                 'rb',
  'Racing Bulls':       'rb',
  'Kick Sauber':        'sauber',
  'Sauber':             'sauber',
}

export function getTeamInfo(teamName) {
  if (!teamName) return null
  const key = TEAM_NAME_MAP[teamName]
  if (key) return TEAM_INFO[key]
  // fuzzy fallback
  const lower = teamName.toLowerCase()
  const match = Object.entries(TEAM_NAME_MAP).find(([k]) => lower.includes(k.toLowerCase()))
  return match ? TEAM_INFO[match[1]] : null
}
